#!/bin/bash
set -e

CMD=$1
case "$CMD" in
  config)
    echo TYPE=php
    echo SERVER_NAME=_
    echo STATIC_LOCATION=/static
    echo STATIC_REWRITE=
    echo STATIC_PATH=/static
    ;;
  build)
    APP=$2
    APP_ROOT=$3
    ;;
  up)
    APP=$2
    APP_ROOT=$3
    ;;
  down)
    APP=$2
    APP_ROOT=$3
    ;;
esac

